db:
  host: "localhost"
  port: "3306"
  user: "root"
  password: "root"
  database: "anypoint"
  
file:
  customer:"C:\Users\sharks\AnypointStudio\studio-workspace\customerapi\src\main\resources\api\examples\customer.json"