#%RAML 1.0 NamedExample


value:
  -
    "id": 1
    "name": "Max"
    "contact_information":
      "address": 
        "street": "Market Street"
        "city": "San Francisco"
        "state": "California"
        "country": "United States"
      "email": "max@mail.com"
      "phno": "+91 (123) 456-7890"
  -
    "id": 2
    "name": "Max mule"
    "contact_information":
      "address": 
        "street": "Market-Street"
        "city": "Santo"
        "state": "London"
        "country": "United States"
      "email": "maxmule@mail.com"
      "phno": "+91 (456) 456-7890"


#################################################################################
# customer:
#   properties:
#     name:
#       type: string
#     contact:
#       type: Contact

# Contact:
#    properties:
#      address:
#        type: Address
#      email:
#        type: Email
#        phno:
#          type: PhoneNumber

# Address:
#     properties:
#       street:
#         type: string
#       city:
#         type: string
#       state:
#         type: string
#       country:
#         type: string

# Email: 
#   pattern: ^[_a-z0-9-]+(\.[_a-z0-9-]+)*@[a-z0-9-]+(\.[a-z0-9-]+)*(\.[a-z]{2,4})$

# PhoneNumber:
#   pattern: ^(\+\d{1,2}\s)?\(?\d{3}\)?[\s.-]\d{3}[\s.-]\d{4}$
